name: quick_grocery
description: EasyGrocer is a cutting-edge mobile application designed to revolutionize your grocery shopping experience.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.9
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  pinput: ^2.2.31
  animated_bottom_navigation_bar: ^1.2.0
  curved_navigation_bar: ^1.0.3
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.2.1+1
  logger: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_localizations:
    sdk: flutter  

flutter:

  uses-material-design: true

  assets:
    - l10n/
    - assets/img/
    - assets/icon/profile/
    - assets/icon/navigation_bar/
